name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * 1,4"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale and will be closed because it has not had recent activity.'
        stale-pr-message: 'This PR has been automatically marked as stale and will be closed because it has not had recent activity.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'feature'	
        exempt-pr-labels: 'feature'
